# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ya-roam-file-storing-service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build 
        rm -rf node_modules/ LICENSE  nest-cli.json  node_modules/ README.org  src/  test/  tsconfig.build.json  tsconfig.json
        ls
        npm install --only=production
        echo Finished
        
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ya-roam-file-storing-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_af6d4630d45e49eda92ec0e1630a4dd8 }}
        package: .
